// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-system-summary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  return ctx.isAuthenticated();
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Please sign in via the MCP OAuth flow." }],
    isError: true
  };
}

// src/lib/mcp/tools/get-system-summary.ts
var get_system_summary_default = defineTool({
  name: "get_system_summary",
  title: "System summary",
  description: "Get counts across the main business entities (clients, suppliers, invoices, POs, bills, bank statements, inventory).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const tables = [
      "clients",
      "suppliers",
      "client_invoices",
      "raw_material_invoices",
      "purchase_orders",
      "po_intake_documents",
      "approvals",
      "quotations",
      "bank_statements",
      "inventory_items",
      "bills"
    ];
    const counts = {};
    await Promise.all(tables.map(async (t) => {
      const { count } = await sb.from(t).select("*", { count: "exact", head: true });
      counts[t] = count || 0;
    }));
    return { content: [{ type: "text", text: JSON.stringify({ counts }, null, 2) }] };
  }
});

// src/lib/mcp/tools/get-clients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var get_clients_default = defineTool2({
  name: "get_clients",
  title: "Get clients",
  description: "List or search clients. Optionally fetch a single client by ID.",
  inputSchema: {
    client_id: z.string().optional().describe("Fetch a single client by UUID."),
    search: z.string().optional().describe("Case-insensitive name search."),
    limit: z.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ client_id, search, limit = 20 }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    if (client_id) {
      const { data: data2, error: error2 } = await sb.from("clients").select("*").eq("id", client_id).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return { content: [{ type: "text", text: JSON.stringify({ client: data2 }, null, 2) }] };
    }
    let q = sb.from("clients").select("*").order("created_at", { ascending: false });
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q.limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ clients: data || [] }, null, 2) }] };
  }
});

// src/lib/mcp/tools/get-suppliers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_suppliers_default = defineTool3({
  name: "get_suppliers",
  title: "Get suppliers",
  description: "List or search suppliers. Optionally fetch a single supplier by ID.",
  inputSchema: {
    supplier_id: z2.string().optional(),
    search: z2.string().optional(),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ supplier_id, search, limit = 20 }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    if (supplier_id) {
      const { data: data2, error: error2 } = await sb.from("suppliers").select("*").eq("id", supplier_id).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return { content: [{ type: "text", text: JSON.stringify({ supplier: data2 }, null, 2) }] };
    }
    let q = sb.from("suppliers").select("*").order("created_at", { ascending: false });
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q.limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ suppliers: data || [] }, null, 2) }] };
  }
});

// src/lib/mcp/tools/get-invoices.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_invoices_default = defineTool4({
  name: "get_invoices",
  title: "Get invoices",
  description: "Fetch client or raw-material invoices with optional status filter.",
  inputSchema: {
    invoice_type: z3.enum(["client", "raw_material"]),
    status: z3.enum(["pending", "awaiting_approval", "approved", "rejected", "all"]).optional(),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ invoice_type, status = "all", limit = 20 }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const table = invoice_type === "client" ? "client_invoices" : "raw_material_invoices";
    let q = sb.from(table).select("*").order("created_at", { ascending: false });
    if (status !== "all") q = q.eq("status", status);
    const { data, error } = await q.limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ invoices: data || [] }, null, 2) }] };
  }
});

// src/lib/mcp/tools/get-bills.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_bills_default = defineTool5({
  name: "get_bills",
  title: "Get bills",
  description: "List bills (extracted from Gmail/uploads).",
  inputSchema: {
    status: z4.string().optional().describe("Optional bill status filter."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit = 20 }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("bills").select("*").order("created_at", { ascending: false });
    if (status) q = q.eq("status", status);
    const { data, error } = await q.limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ bills: data || [] }, null, 2) }] };
  }
});

// src/lib/mcp/tools/get-inventory.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_inventory_default = defineTool6({
  name: "get_inventory_status",
  title: "Inventory status",
  description: "List inventory items, optionally filtered to low-stock items only.",
  inputSchema: {
    low_stock_only: z5.boolean().optional(),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ low_stock_only = false, limit = 50 }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("inventory_items").select("*").eq("is_active", true).order("current_quantity").limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = data || [];
    const low = items.filter((i) => i.current_quantity <= i.minimum_threshold);
    return {
      content: [{
        type: "text",
        text: JSON.stringify({ items: low_stock_only ? low : items, low_stock_count: low.length }, null, 2)
      }]
    };
  }
});

// src/lib/mcp/tools/get-purchase-orders.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var get_purchase_orders_default = defineTool7({
  name: "get_purchase_orders",
  title: "Get purchase orders",
  description: "List purchase orders from the PO intake pipeline.",
  inputSchema: {
    status: z6.string().optional(),
    limit: z6.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit = 20 }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("po_orders").select("*").order("created_at", { ascending: false });
    if (status) q = q.eq("status", status);
    const { data, error } = await q.limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ orders: data || [] }, null, 2) }] };
  }
});

// src/lib/mcp/tools/get-approvals.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^3.25.76";
var get_approvals_default = defineTool8({
  name: "get_approvals",
  title: "Get approvals",
  description: "List approval requests.",
  inputSchema: {
    status: z7.enum(["pending", "approved", "rejected", "all"]).optional(),
    limit: z7.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status = "all", limit = 20 }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("approvals").select("*").order("created_at", { ascending: false });
    if (status !== "all") q = q.eq("status", status);
    const { data, error } = await q.limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ approvals: data || [] }, null, 2) }] };
  }
});

// src/lib/mcp/tools/update-approval.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z8 } from "npm:zod@^3.25.76";
var update_approval_default = defineTool9({
  name: "update_approval_status",
  title: "Approve or reject",
  description: "Approve or reject a pending approval request.",
  inputSchema: {
    approval_id: z8.string(),
    action: z8.enum(["approved", "rejected"]),
    comment: z8.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ approval_id, action, comment }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("approvals").update({
      status: action,
      comment: comment || `${action} via MCP`,
      approved_by: ctx.getUserEmail() || ctx.getUserId() || "mcp",
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    }).eq("id", approval_id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ success: true, approval: data }, null, 2) }] };
  }
});

// src/lib/mcp/tools/create-reorder.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z9 } from "npm:zod@^3.25.76";
var create_reorder_default = defineTool10({
  name: "create_reorder_request",
  title: "Create reorder request",
  description: "Create a reorder request for a low-stock inventory item.",
  inputSchema: {
    inventory_item_id: z9.string(),
    quantity: z9.number().positive(),
    supplier_id: z9.string().optional(),
    note: z9.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async ({ inventory_item_id, quantity, supplier_id, note }, ctx) => {
    if (!requireAuth(ctx)) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data: item } = await sb.from("inventory_items").select("*").eq("id", inventory_item_id).maybeSingle();
    if (!item) return { content: [{ type: "text", text: "Item not found" }], isError: true };
    const { data, error } = await sb.from("reorder_requests").insert({
      inventory_item_id,
      quantity_requested: quantity,
      supplier_id: supplier_id || item.preferred_supplier_id,
      quantity_at_trigger: item.current_quantity,
      minimum_threshold_at_trigger: item.minimum_threshold,
      internal_note: note || "Reorder via MCP",
      status: "sent"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify({ success: true, reorder: data }, null, 2) }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pskuxhpfohmxlhmupeoz";
var mcp_default = defineMcp({
  name: "talligence-mcp",
  title: "Talligence MCP",
  version: "1.0.0",
  instructions: "Read and act on Talligence business data (clients, suppliers, invoices, bills, purchase orders, inventory, approvals). All calls are scoped to the signed-in user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_system_summary_default,
    get_clients_default,
    get_suppliers_default,
    get_invoices_default,
    get_bills_default,
    get_inventory_default,
    get_purchase_orders_default,
    get_approvals_default,
    update_approval_default,
    create_reorder_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
